print("=== Your Adventure Simulator ===")
print("You will be asked some questions, answer those questions to start your adventure.")
print(" ")
print("lets start")
print(" ")
print("What is your name?")
name = input()
print(" ")
print("How old are you?")
age = input()
print(" ")
print("What do you like to do?")
hobby = input()
print(" ")
print("What music do you like to listen to?")
music = input()
print(" ")
print("Results Coming Up")
print(" ")
print("My name is", name, "and I am", age, "years old.", "In my free time I like to", hobby, "and while doing", hobby, "I like to listen to ", music, "." )
